[project]
name = "querypath"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dateparser>=1.2.2",
    "llama-cpp-python>=0.3.13",
    "python-dateutil>=2.9.0.post0",
]
